[build-system]
requires = ["setuptools-scm>=3.2.0",
            "setuptools_scm_git_archive",
            "numpy>=2.0.0",
            "cython>=0.29",
            "setuptools>=61.0",
            "scipy>=1.12.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pygom"
#dynamic = ["version"]
version = "0.1.8a"
dependencies = [
  "dask[complete]>=0.13.0",
  "graphviz>=0.4.9",
  "matplotlib>=1.0.0",
  "numpy>=2.0.0",
  "pandas>=2.2.2",
  "python-dateutil>=2.0.0",
  "scipy>=1.4.1",
  "sympy>=1.0.0",
  "numpydoc>=0.6.0",
  "cython>=0.29"
]
authors = [
  {name="Edwin Tye"},
  {name="Thomas Finnie", email="thomas.finnie@ukhsa.gov.uk"},
  {name="Hannah Williams"},
  {name="Jonty Carruthers"},
  {name="Martin Grunnill"},
  {name="Joe Gibson", email="joseph.gibson@ukhsa.gov.uk"}
]

description = "ODE modeling in Python."
readme = "README.md"
requires-python = ">=3.8"


classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GPL2",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
# version = {attr = "0.1.8a"} # TODO: change to git tag
readme = {file = ["README.rst"]}

[project.urls]
Homepage = "http://ukhsa-collaboration.github.io/pygom/md/intro.html"
Issues = "https://github.com/ukhsa-collaboration/pygom/issues"
