name: pygom

on:
  push:
    branches:
      - master
      - dev
      - feature/*
      - bugfix/*

  pull_request:
    branches:
      - master
      - dev

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  #, macos-13, macos-14] 
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/cache@v4
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/cache@v4
        if: startsWith(runner.os, 'Windows')
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check python version
        run: python -c "import sys; print(sys.version)"
        
      - name: Install pip 
        run: |
          python -m pip install --upgrade pip
          
      - name: install PyGOM
        run: |
          pip install .

      - name: Run tests
        run: python -m unittest discover --verbose --start-directory tests

  build_wheels:
    name: Build wheels on ${{ matrix.platform_id }} for Python v${{ matrix.python[1] }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
          # Window 64 bit
          - os: windows-latest
            python: [cp39, "3.9"]
            platform_id: win_amd64
          - os: windows-latest
            python: [cp310, "3.10"]
            platform_id: win_amd64
          - os: windows-latest
            python: [cp311, "3.11"]
            platform_id: win_amd64
          - os: windows-latest
            python: [cp312, "3.12"]
            platform_id: win_amd64

          # Python 3.9 in the manylinux build environment requires our dependencies to be
          # built from source so we won't supply a wheel for 3.9 (source build will prevent lib
          # version conflicts).

          # NumPy on Python 3.10 only supports 64bit and is only available with manylinux2014
          - os: ubuntu-latest
            python: [cp310, "3.10"]
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: [cp311, "3.11"]
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: [cp312, "3.12"]
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python[1] }}

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel>=2.19.2

      - name: Build and test the wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.python[0] }}-${{ matrix.platform_id }}*
          CIBW_TEST_COMMAND: python -W default -m unittest discover --start-directory {project}/tests

      # Upload the results
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.platform_id }}-${{ matrix.python[0] }}
          path: ./wheelhouse/*.whl
